"""
View Dashboard Data

Quick viewer for Parquet dashboard files generated by the ETL pipeline.
Shows summary statistics, top providers, top diagnoses, and time series data.
"""

import sys
from pathlib import Path
import pandas as pd


def print_banner(text):
    """Print a formatted banner"""
    print("\n" + "=" * 80)
    print(f"  {text}")
    print("=" * 80 + "\n")


def print_section(title):
    """Print a section header"""
    print(f"\n--- {title} ---")


def view_dashboard_data(dashboard_dir: str = "../data/etl/analytics/dashboards/medical-claims"):
    """
    View all dashboard Parquet files

    Args:
        dashboard_dir: Path to dashboard directory
    """
    dashboard_path = Path(dashboard_dir)

    if not dashboard_path.exists():
        print(f"❌ Error: Dashboard directory not found: {dashboard_path}")
        print(f"   Run the ETL pipeline first: python test_comprehensive_pipeline.py")
        return 1

    print_banner("Dashboard Data Viewer")
    print(f"Dashboard directory: {dashboard_path}\n")

    # ========================================================================
    # 1. Overall Summary
    # ========================================================================
    summary_file = dashboard_path / "claims_summary.parquet"
    if summary_file.exists():
        print_section("📊 Overall Summary")
        df_summary = pd.read_parquet(summary_file)
        print(df_summary.to_string(index=False))
    else:
        print("⚠️  Summary file not found")

    # ========================================================================
    # 2. By Provider
    # ========================================================================
    provider_file = dashboard_path / "claims_by_provider.parquet"
    if provider_file.exists():
        print_section("👨‍⚕️ Top 10 Providers by Total Billed")
        df_provider = pd.read_parquet(provider_file)

        # Show top 10 by total billed
        if 'total_billed' in df_provider.columns:
            top_providers = df_provider.nlargest(10, 'total_billed')
        else:
            top_providers = df_provider.head(10)

        print(top_providers.to_string(index=False))
        print(f"\nTotal providers: {len(df_provider)}")
    else:
        print("⚠️  Provider file not found")

    # ========================================================================
    # 3. By Diagnosis
    # ========================================================================
    diagnosis_file = dashboard_path / "claims_by_diagnosis.parquet"
    if diagnosis_file.exists():
        print_section("🏥 Top 10 Diagnoses by Claim Count")
        df_diagnosis = pd.read_parquet(diagnosis_file)

        # Show top 10 by claim count
        if 'total_claims' in df_diagnosis.columns:
            top_diagnoses = df_diagnosis.nlargest(10, 'total_claims')
        else:
            top_diagnoses = df_diagnosis.head(10)

        print(top_diagnoses.to_string(index=False))
        print(f"\nTotal diagnoses: {len(df_diagnosis)}")
    else:
        print("⚠️  Diagnosis file not found")

    # ========================================================================
    # 4. Time Series
    # ========================================================================
    date_file = dashboard_path / "claims_by_date.parquet"
    if date_file.exists():
        print_section("📅 Time Series (Daily)")
        df_date = pd.read_parquet(date_file)

        # Show all dates
        print(df_date.to_string(index=False))

        # Calculate date range
        if 'date' in df_date.columns and len(df_date) > 0:
            min_date = df_date['date'].min()
            max_date = df_date['date'].max()
            print(f"\nDate range: {min_date} to {max_date}")
            print(f"Total days: {len(df_date)}")
    else:
        print("⚠️  Date file not found")

    print_banner("✅ Dashboard Data Review Complete")

    return 0


def main():
    """Main entry point"""
    # Accept optional dashboard directory as argument
    if len(sys.argv) > 1:
        dashboard_dir = sys.argv[1]
    else:
        dashboard_dir = "../data/etl/analytics/dashboards/medical-claims"

    return view_dashboard_data(dashboard_dir)


if __name__ == "__main__":
    sys.exit(main())
